blueprint:
  name: EH Set Master Door Code
  description: "A script that sets a temporary code for smart door locks"
  domain: script
  author: EffortlessHome
  input:
    lock:
      description: (Required) Which door lock to program
      name: Lock
      selector:
        target:
          entity:
            domain: lock
    lock_name:
      name: Lock Name
      description: The friendly name of the lock in HA
      default: doorlock
    slot:
      description: (Required) Which code slot to use (0-29)
      name: Slot
      default: 1
      selector:
        text:
    on_start:
      description: (Optional) Action to execute when code is enabled

        The lock entity is available via the "lock" variable.
        The set code is available via the "code" variable.
        The set code slot is available via the "slot" variable.
        The validity time is available via the "duration" variable.
      name: When code enabled
      default: []
      selector:
        action:

    additional_actions:
      name: Additional Actions
      description: Add additional actions to execute (Optional)
      default: []
      selector:
        action: {}
variables:
  lock: !input lock
  slot: !input slot
  lock_name: !input lock_name

sequence:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/{{ lock_name }}/set
      payload: >-
        {"pin_code": {"user": "{{ slot }}", "user_type": "unrestricted", "user_enabled":
        "true", "pin_code": "{{ states('input_text.templockcodownerslockcode_pin') }}"}}
  - choose:
      - conditions: "{{ true }}"
        sequence: !input on_start
  - choose: []
    default: !input additional_actions

mode: single
