config:
  input_text:
    templockcode_pin:
      name: "templockcode_pin"
      icon: "mdi:lock-smart"
      max: 4
      mode: "text"
      min: 0
      pattern: "/^\\d{4}$/"

    ownerslockcode_pin:
      max: 4
      mode: "text"
      icon: "mdi:lock-smart"
      name: "ownerslockcode_pin"
      min: 0
      pattern: "/^\\d{4}$/"

    currentrenterpincode:
      name: "CurrentRenterPinCode"
      max: 4
      min: 0
      mode: "text"
