blueprint:
  name: Camera Person Detection with Oasira AI
  description:
    This automation blueprint converts a non-person detecting camera to a person detecting camera using Oasira AI. It uses the
    camera motion trigger to analyze the snapshot for a person in the image and allows taking actions based on the results.
  domain: automation
  author: EffortlessHome
  input:
    sensor:
      name: Camera Motion Binary Sensor
      description: The sensor wich triggers the person detection
      selector:
        entity:
          domain:
            - binary_sensor
          multiple: false
    camera:
      name: Camera
      description: The camera which creates the snapshot
      selector:
        entity:
          domain:
            - camera
          multiple: false
    person_input:
      name: Person
      description: The person (or people) to notify
      selector:
        entity:
          multiple: true
          filter:
            domain: person
    notification_title:
      name: Notification title
      description: 'Default: "Person detected!"'
      default: Person detected!
    notification_message:
      name: Notification message
      description:
        'Default: "{{ sensor_name }} detected a person! Snapshot from {{
        camera_name }} at {{ time }}."'
      default:
        "{{ sensor_name }} detected a person! Snapshot from {{ camera_name
        }} at {{ time }}."

    data_clickaction_url:
      name: URL to Navigate (Optional)
      description:
        The URL to navigate to when clicking on the notification. (default
        = /lovelace)
      default: /lovelace

    additional_actions:
      name: Additional Actions
      description: Add additional actions to execute (Optional)
        else.
      default: []
      selector:
        action: {}

trigger:
  - platform: state
    entity_id: !input sensor
    to: "on"
variables:
  sensor: !input sensor
  sensor_name: "{{ states[sensor].name }}"
  camera: !input camera
  camera_name: "{{ states[camera].name }}"

  time: '{{ now().strftime("%H:%M") }}'
  date: '{{ now().strftime("%Y-%m-%d") }}'
  notification_title: !input notification_title
  notification_message: !input notification_message

  snapshot_create_file_path: /media/snapshots/{{ camera_name }}/{{
    now().strftime("%Y%m%d-%H%M%S") }}.jpg
  snapshot_access_file_path:
    "{{ snapshot_create_file_path | replace('/media','/media/local')
    }}"

  clickActionURL: !input data_clickaction_url

  additional_actions: !input additional_actions

action:
  - service: camera.snapshot
    entity_id: !input camera
    data:
      filename: "{{ snapshot_create_file_path }}"

  - data:
      prompt: >-
        Very briefly describe what you see in this image from my
        camera. Your message needs to be short to fit in a phone notification.
        Don't describe stationary objects or buildings.
      image_filename: "{{ snapshot_create_file_path }}"
    response_variable: content
    action: oasira.generate_aigen_content_service

  - condition: template
    value_template: "{{ 'man' or 'boy' or 'woman' or 'girl' or 'person' in content.text}}"

  - condition: state
    entity_id: binary_sensor.motion_notification_sensor
    state: "on"

  - service: oasira.notify_person_service
    data:
      target: !input person_input
      title: !input notification_title
      message: "{{ notification_message}} {{content.text}}"
      data:
        image: "{{ snapshot_access_file_path }}"
        clickAction: !input data_clickaction_url
        ttl: 0
        priority: high
        attachment:
          url: "{{ snapshot_access_file_path }}"
          content_type: JPEG
        url: !input data_clickaction_url
        actions:
          - action: SNOOZEMOTIONNOTIFY
            title: Snooze Motion Notifications

  - choose: []
    default: !input additional_actions
mode: parallel
