blueprint:
  name: Good Morning
  description: At morning, disarm alarm and turn off sleeping sensor
  domain: automation
  author: EffortlessHome
  input:
    goodmorning_time:
      name: What time of the day will goodmorning run
      description: The time of day when this will run each day.
      default: "07:00:00"
      selector:
        time: {}

    securityalarm:
      name: Security Alarm
      description: The security alarm to disarm
      selector:
        entity:
          filter:
            - domain:
                - alarm_control_panel
          multiple: false
    additional_actions:
      name: Additional Actions
      description: Add additional actions to execute (Optional)
      default: []
      selector:
        action: {}
trigger:
  - platform: time
    at: !input goodmorning_time
condition:
  - condition: state
    entity_id: binary_sensor.someone_home_sensor
    state: "on"
action:
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.switch_sleep_mode
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - service: alarm_control_panel.alarm_disarm
    data:
      entity_id: !input securityalarm
  - choose: []
    default: !input additional_actions
