blueprint:
  name: Humidity Alarm Triggered
  description: Set the actions to take when a humidity alarm is triggered
  domain: automation
  author: EffortlessHome
  input:
    humidsensor:
      name: Humidity Sensor
      description: The triggering humidity sensor(s)
      selector:
        entity:
          filter:
            - domain:
                - sensor
          multiple: true
    high_sensor:
      name: High Humidity Value Sensor
      description: The sensor that provides the level of humidity configured to trigger an alert.
      default: sensor.config_highhumidity
      selector:
        entity:
          domain: sensor
    low_sensor:
      name: Low Humidity Value Sensor
      description: The sensor that provides the level of humidity configured to trigger an alert.
      default: sensor.config_lowhumidity
      selector:
        entity:
          domain: sensor
    person_input:
      name: Person
      description: The person (or people) to notify
      selector:
        entity:
          multiple: true
          filter:
            domain: person
    notification_message:
      name: Notification message
      description: "Humidity Sensor Activated Message"
      default: "Humidity Sensor Activated."

    data_clickaction_url:
      name: URL to Navigate (Optional)
      description:
        The URL to navigate to when clicking on the notification. (default
        = /lovelace)
      default: /lovelace

    additional_actions:
      name: Additional Actions
      description: Add additional actions to execute (Optional)
      default: []
      selector:
        action: {}

trigger:
  - platform: numeric_state
    entity_id: !input humidsensor
    above: !input high_sensor
  - platform: numeric_state
    entity_id: !input humidsensor
    below: !input low_sensor
variables:
  clickActionURL: !input data_clickaction_url

action:
  - service: oasira.notify_person_service
    data:
      target: !input person_input
      title: Humidity Sensor Activated
      message: !input notification_message
      data:
        clickAction: !input data_clickaction_url
        ttl: 0
        priority: high
        url: !input data_clickaction_url

  - choose: []
    default: !input additional_actions
