blueprint:
  name: Motion-activated Light with Illuminance
  description:
    Turn on a light when motion is detected and illuminance is below a
    set Lux level. The light will dim before it is turned off to signal that it has
    not detected motion in quite a while. There is also two timers, on for daytime
    and one for nighttime. Use label "SleepArea" on any lights you do not want to turn on while sleeping.
  domain: automation
  author: EffortlessHome
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain:
            - binary_sensor
            - group
          multiple: false
    lux_entity:
      name: Illuminance Sensor
      selector:
        entity:
          domain:
            - sensor
          #device_class:
          #  - illuminance
          multiple: false
    lux_level:
      name: Illuminance level
      description:
        If lux is below this value and motion is detected, the light will
        turn on.
      default: 100
      selector:
        number:
          min: 0.0
          max: 1000.0
          step: 1.0
          mode: slider
    light_target:
      name: Light
      selector:
        target:
          entity:
            - domain:
                - light
    dim_time:
      name: Dim light
      description:
        The light will start dim this many seconds before it is turned
        off if no motion has been detected to signal that the light will soon turn
        off.
      default: 30
      selector:
        number:
          min: 0.0
          max: 120.0
          unit_of_measurement: seconds
          step: 1.0
          mode: slider

    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected
      default: 120
      selector:
        number:
          min: 0.0
          max: 600.0
          unit_of_measurement: seconds
          step: 1.0
          mode: slider
    additional_actions:
      name: Additional Actions
      description: Add additional actions to execute (Optional)
      default: []
      selector:
        action: {}
mode: restart
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input motion_entity
  from: "off"
  to: "on"

condition:
  condition: and
  conditions:
    - condition: numeric_state
      entity_id: !input lux_entity
      below: !input lux_level

action:
  - variables:
      mylight: !input light_target #light.area_lights_bedroom
      valuequery: '{{ "sleeparea" not in labels(mylight.entity_id)  }}'

      valuetemplate: "{{ valuequery }}"

  - condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.sleeping_sensor
        state: "off"
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.sleeping_sensor
            state: "on"
          - condition: template
            value_template: >
              {{ valuetemplate }}

  - service: light.turn_on
    target: !input light_target

  - wait_for_trigger:
      platform: state
      entity_id: !input motion_entity
      from: "on"

  - delay: !input no_motion_wait

  - service: light.turn_off
    target: !input light_target
    data:
      transition: !input dim_time

  - choose: []
    default: !input additional_actions
