blueprint:
  name: Medical Alert Alarm Triggered Notification
  description: Set the actions to take when the medical alert alarm is triggered.
  domain: automation
  author: EffortlessHome
  input:
    person_input:
      name: Person
      description: The person (or people) to notify
      selector:
        entity:
          multiple: true
          filter:
            domain: person
    notification_message:
      name: Notification message
      description: The notification message to send when the Medical Alert Alarm has been triggered.
      default: Medical Alert Alarm has been triggered.
    timeout_seconds:
      name: Timeout in seconds
      description: Time after which the confirm action will be automatically triggered if no response is received
      default: 300
      selector:
        number:
          min: 100
          max: 600
          unit_of_measurement: seconds
    additional_actions:
      name: Additional Actions
      description: Add additional actions to execute (Optional)
      default: []
      selector:
        action: {}
trigger:
  - platform: state
    entity_id: binary_sensor.medical_alert_sensor
    to: "on"
action:
  - alias: Set up variables
    variables:
      action_confirm: "{{ 'CONFIRM_' ~ context.id }}"
      action_dismiss: "{{ 'DISMISS_' ~ context.id }}"
  - service: oasira.notify_person_service
    data:
      target: !input person_input
      message: !input notification_message
      title: "Security Alarm Triggered"
      data:
        actions:
          - action: "{{ action_confirm }}"
            title: "Confirm Alarm"
          - action: "{{ action_dismiss }}"
            title: "Disarm Alarm"
  - alias: Awaiting response
    wait_for_trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "{{ action_confirm }}"
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "{{ action_dismiss }}"
    timeout:
      seconds: !input timeout_seconds
  - choose:
      - conditions: "{{ wait.trigger.event.data.action == action_confirm }}"
        sequence:
          - action: oasira.confirmpendingalarmservice
            data: {}

      - conditions: "{{ wait.trigger.event.data.action == action_dismiss }}"
        sequence:
          - action: oasira.cancelalarmservice
            metadata: {}
            data: {}
          - action: switch.turn_off
            metadata: {}
            data: {}
            target:
              entity_id: switch.medicalalertalarm

    default: # If timeout occurs
      - sequence:
          - action: oasira.confirmpendingalarmservice
            data: {}

  - choose: []
    default: !input additional_actions
