blueprint:
  name: Motion Activated Light(s)
  description: Turn on a light when motion is detected
  domain: automation
  author: EffortlessHome
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain:
            - group
            - binary_sensor
          multiple: false

    light_target:
      name: Light
      selector:
        target:
          entity:
            - domain:
                - light
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0.0
          max: 3600.0
          unit_of_measurement: seconds
          step: 1.0
          mode: slider
    additional_actions:
      name: Additional Actions
      description: Add additional actions to execute (Optional)
      default: []
      selector:
        action: {}
mode: restart
max_exceeded: silent
trigger:
  platform: state
  entity_id: !input motion_entity
  from: "off"
  to: "on"
action:
  - alias: Turn on the light
    service: light.turn_on
    target: !input light_target
  - alias: Wait until there is no motion from device
    wait_for_trigger:
      platform: state
      entity_id: !input motion_entity
      from: "on"
      to: "off"
  - alias: Wait the number of seconds that has been set
    delay: !input no_motion_wait
  - alias: Turn off the light
    service: light.turn_off
    target: !input light_target
  - choose: []
    default: !input additional_actions
