blueprint:
  name: Actions and Notification When No Motion
  description: Actions to take if there is no motion detected within the provided timeframe and someone is home and not sleeping.
  domain: automation
  author: EffortlessHome
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain:
            - group
            - binary_sensor
          multiple: false

    no_motion_wait:
      name: Wait time
      description: The amount of time to check for no motion to trigger.
      default: 120
      selector:
        number:
          min: 0.0
          max: 86000.0
          unit_of_measurement: seconds
          step: 1.0
          mode: slider

    person_input:
      name: Person
      description: The person (or people) to notify
      selector:
        entity:
          multiple: true
          filter:
            domain: person

    notification_message:
      name: Notification message
      description: "No Motion Detected Message"
      default: "No motion detected for configured time period while someone is home and not sleeping."

    data_clickaction_url:
      name: URL to Navigate (Optional)
      description:
        The URL to navigate to when clicking on the notification. (default
        = /lovelace)
      default: /lovelace

    additional_actions:
      name: Additional Actions
      description: Add additional actions to execute (Optional)
      default: []
      selector:
        action: {}

trigger:
  platform: state
  entity_id: !input motion_entity
  from: "on"
  to: "off"
  for: !input no_motion_wait

variables:
  clickActionURL: !input data_clickaction_url

conditions:
  - condition: state
    entity_id: binary_sensor.someone_home_sensor
    state: "on"
  - condition: state
    entity_id: binary_sensor.sleeping_sensor
    state: "off"
action:
  - service: oasira.notify_person_service
    data:
      target: !input person_input
      title: No Motion Detected
      message: !input notification_message
      data:
        clickAction: !input data_clickaction_url
        ttl: 0
        priority: high
        url: !input data_clickaction_url

  - choose: []
    default: !input additional_actions
