blueprint:
  name: Smart Appliance Conversion End Automation
  description: Set the end run action(s) to take to convert a dumb appliance to smart
  domain: automation
  author: EffortlessHome
  input:
    powermonitoringsensor:
      name: Power Monitoring Sensor
      description:
        The power monitoring sensor attached to the appliance. Typically
        a smart plug.
      selector:
        entity:
          filter:
            - domain:
                - sensor
          multiple: false
    trigger_poweruseage:
      description: The amount of power usage to trigger the stopped state
      name: Trigger Power Usage
      default: 5
      selector:
        number:
          min: 0.0
          max: 99.0
          unit_of_measurement: watts
          step: 1.0
          mode: slider
    powerusagelevel_time:
      name: Power Usage Time At Level
      description:
        How long in seconds should the power usage be at that amount to
        confirm appliance stopped?
      default: 300
      selector:
        number:
          min: 0.0
          max: 900.0
          unit_of_measurement: seconds
          mode: slider
          step: 1.0
    appliance_switch:
      name: Dedicated appliance switch
      description: Use one of the EffortlessHome defined Appliance Switches to convert the appliance to smart.
      selector:
        entity:
          domain:
            - switch
          multiple: false
    person_input:
      name: Person
      description: The person (or people) to notify
      selector:
        entity:
          multiple: true
          filter:
            domain: person
    notification_message:
      name: Notification message
      description: "Default: Appliance Stopped"
      default: Appliance Stopped

    data_clickaction_url:
      name: URL to Navigate (Optional)
      description:
        The URL to navigate to when clicking on the notification. (default
        = /lovelace)
      default: /lovelace

    additional_actions:
      name: Additional Actions
      description: Add additional actions to execute (Optional)
      default: []
      selector:
        action: {}

trigger:
  - platform: numeric_state
    entity_id: !input powermonitoringsensor
    below: !input trigger_poweruseage
    for:
      hours: 0
      minutes: 0
      seconds: !input powerusagelevel_time
condition:
  - condition: state
    entity_id: !input appliance_switch
    state: "on"
variables:
  clickActionURL: !input data_clickaction_url

action:
  - service: oasira.notify_person_service
    data:
      target: !input person_input
      title: !input notification_message
      message: !input notification_message
      data:
        clickAction: !input data_clickaction_url
        ttl: 0
        priority: high
        url: !input data_clickaction_url

  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: !input appliance_switch

  - choose: []
    default: !input additional_actions
