generate_content:
  fields:
    prompt:
      required: true
      selector:
        text:
          multiline: true
    image_filename:
      required: false
      selector:
        object:

cloudbackupservice:
  description: Service to backup the configuration to the cloud
  fields:
    prompt:
      name: Prompt
      description: The prompt to show in the notification
      example: Backup configuration to the cloud
    image_filename:
      name: Image filename
      description: The image filename to show in the notification
      example: /local/cloudbackup.png

createcleanmotionfilesservice:
  description: Service to clean motion files
  fields:
    prompt:
      name: Prompt
      description: The prompt to show in the notification
      example: Create clean motion files
    image_filename:
      name: Image filename
      description: The image filename to show in the notification
      example: /local/cleanmotionfiles.png

notify_person_service:
  description: Notify a person
  fields:
    person:
      name: Person
      description: The person to notify
      example: 'John Doe'
    message:
      name: Message
      description: The message to send
      example: 'Hello, this is a notification'
    title:
      name: Title
      description: The title of the notification
      example: 'Notification'
    image_filename:
      name: Image filename
      description: The image filename to show in the notification
      example: /local/notify.png

generate_aigen_content_service:
  description: Generate AI generated content
  fields:
    prompt:
      name: Prompt
      description: The prompt to generate content from
      example: 'A prompt to generate content from'
    image_filename:
      name: Image filename
      description: The image filename to show in the notification
      example: /local/aigencontent.png

generateautomationsuggestions:
  description: Generate automation suggestions
  fields:
    prompt:
      name: Prompt
      description: The prompt to show in the notification
      example: Generate automation suggestions
    image_filename:
      name: Image filename
      description: The image filename to show in the notification
      example: /local/automationsuggestions.png

generateentityautomationsuggestions:
  description: Generate entity automation suggestions
  fields:
    prompt:
      name: Prompt
      description: The prompt to show in the notification
      example: Generate entity automation suggestions
    image_filename:
      name: Image filename
      description: The image filename to show in the notification
      example: /local/entityautomationsuggestions.png

confirmpendingalarmservice:
  description: Confirm pending alarms
  fields:
    prompt:
      name: Prompt
      description: The prompt to show in the notification
      example: Confirm pending alarm
    image_filename:
      name: Image filename
      description: The image filename to show in the notification
      example: /local/confirmpendingalarm.png

cancelalarmservice:
  description: Cancel alarm
  fields:
    prompt:
      name: Prompt
      description: The prompt to show in the notification
      example: Cancel alarm
    image_filename:
      name: Image filename
      description: The image filename to show in the notification
      example: /local/cancelalarm.png

getalarmstatusservice:
  description: Get alarm status
  fields:
    prompt:
      name: Prompt
      description: The prompt to show in the notification
      example: Get alarm status
    image_filename:
      name: Image filename
      description: The image filename to show in the notification
      example: /local/getalarmstatus.png