arm:
  fields:
    entity_id:
      example: "alarm_control_panel.alarm"
      required: true
      selector:
        entity:
          integration: oasira
          domain: alarm_control_panel
    code:
      example: "1234"
      required: false
      selector:
        text:
    mode:
      example: "away"
      required: false
      default: away
      selector:
        select:
          translation_key: "arm_mode"
          options:
            - away
            - night
            - home
            - vacation
            - custom
    skip_delay:
      example: false
      required: false
      default: false
      selector:
        boolean:
    force:
      example: false
      required: false
      default: false
      selector:
        boolean:
disarm:
  fields:
    entity_id:
      example: "alarm_control_panel.alarm"
      required: true
      selector:
        entity:
          integration: oasira
          domain: alarm_control_panel
    code:
      example: "1234"
      required: false
      selector:
        text:
enable_user:
  fields:
    name:
      example: "Frank"
      required: true
      selector:
        text:
disable_user:
  fields:
    name:
      example: "Frank"
      required: true
      selector:
        text:

generate_content:
  fields:
    prompt:
      required: true
      selector:
        text:
          multiline: true
    image_filename:
      required: false
      selector:
        object:
start:
  name: Presence simulation start
  description: Start the presence simulation
  fields:
    switch_id:
      name: The id of the presence simulation switch
      description: The id of the presence simulation switch
      example: switch.presence_simulation_2
    entity_id:
      name: Entities list
      description: The list of entities to use by the presence simulation to override the list configured in the component
      example: >
        - group.outside_lights
    delta:
      name: Delta
      description: Override the default number of days used by the simulation
      example: 7
    restore_states:
      name: Should presence simulation status be restored after restart
      description: Override the default restore switch. If set, the states will be restored after the simulation
      example: True
    random:
      name: Activate random
      description: Add a random factor (in seconds) to the historic events
      example: 300
stop:
  description: Stop the presence simulation
  name: Presence simulation stop
  fields:
    switch_id:
      name: The id of the presence simulation switch
      description: The id of the presence simulation switch
      example: switch.presence_simulation_2
toggle:
  description: Toggle the presence simulation
  name: Presence simulation toggle
  fields:
    switch_id:
      name: The id of the presence simulation switch
      description: The id of the presence simulation switch
      example: switch.presence_simulation_2
